#!/bin/bash

set -e

D=riscof_work
TARGET=${1:-rv32i_m/I/src/and-01.S}

MAKEFILE_DUT=Makefile.DUT-minimax
if [ ! -e $D/$MAKEFILE_DUT ]
then
	echo $D/$MAKEFILE_DUT did not exist. Run full RISCOF suite first. > /dev/stderr
	exit 1
fi
TARGET_DUT=`awk -v TARGET="$TARGET" "/:$/ {T=\\$1}; \\$0 ~ TARGET { print T; exit; }" $D/$MAKEFILE_DUT`
SIGNATURE_DUT=$D/$TARGET/ref/*.signature

MAKEFILE_REF=Makefile.Reference-sail_c_simulator
if [ ! -e $D/$MAKEFILE_REF ]
then
	echo $D/$MAKEFILE_REF did not exist. Run full RISCOF suite first. > /dev/stderr
	exit 2
fi
TARGET_REF=`awk -v TARGET="$TARGET" "/:$/ {T=\\$1}; \\$0 ~ TARGET { print T; exit; }" $D/$MAKEFILE_REF`
SIGNATURE_REF=$D/$TARGET/dut/*.signature

rm -f $SIGNATURE_DUT $SIGNATURE_REF

make -C $D -f $MAKEFILE_DUT $TARGET_DUT
make -C $D -f $MAKEFILE_REF $TARGET_REF

diff -us $SIGNATURE_DUT $SIGNATURE_REF
