name: CI

on: [push, pull_request]

jobs:
  compliance:
    name: Regression Tests
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        path: minimax

    - name: Run regression tests
      run: make -C minimax/test

    - name: Archive test report
      uses: actions/upload-artifact@v3
      with:
        name: regression-test-report
        path: |
          minimax/test/riscof_work/report.html
          minimax/test/riscof_work/style.css
